### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by Pranavv0307** [AdityaJS12321/XGen#1]
Gib credit ra waste!

**Comment by adityajs12321** [comment]
for what ra?
app totally made by me

**Comment by Neelgodly** [comment]
lmfao but there is a bunch of other apps called x-gen

**Comment by adityajs12321** [comment]
yes, and your username too is no exception 

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/77228612/153834054-788fd7da-0b1e-4df1-9269-f6d6b46f479f.png">

**Comment by Neelgodly** [comment]
ny username doesnt have space

**Comment by adityajs12321** [comment]
well you obviously need to distinguish between them so
